POST https://cursonode-c731.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Este é o Video 01",
    "duration": 180
}

###

GET https://cursonode-c731.onrender.com/videos

###

PUT https://cursonode-c731.onrender.com/videos/2d554e06-0164-4b3d-9614-a7fb28a76596
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Este é o Video 02",
    "duration": 180
}

###

DELETE https://cursonode-c731.onrender.com/videos/2d554e06-0164-4b3d-9614-a7fb28a76596